#!/bin/bash
if [ -z "$1" ]; then
    echo "Usage rdb [-v=<ver>] <data_dir>"
    exit 1
fi
version="rethinkdb-next"
datadir=""
case "$1" in
    -v=*)
        ver=$(echo "$1" | tr -d "\-v=")
        version="rel-${ver}"
        datadir="$2"
        shift
        ;;
    -b)
        version="rethinkdb-branches"
        datadir="$2"
        shift
        ;;
    *)
        datadir=$1
        ;;
esac
shift
if [ -z "$datadir" ]; then
    echo "No database specified"
    echo "Usage rdb [-v=<ver>] data_dir"
    exit 2
fi
CMD="/home/alex/workspace/${version}/build/release/rethinkdb"

echo "Version: $version"
echo "Command: $CMD"
echo "Options: $@"
echo "Data   : $datadir"
echo ""

if [ ! -d "$datadir" ]; then
    echo "Database $datadir doesn't exist. Creating it..."
    echo ""
    "$CMD" create -d "$datadir"
fi
"$CMD" serve --bind all -d "$datadir" $@
