#!/bin/bash
if [ -h $0 ]; then
    SLINK=`ls -l $0 | awk '{print $11}'`;
    DIR=`dirname $SLINK`
else
    DIR=`dirname $0`
fi
"$DIR/smartfinder" -d=~/Dropbox/Elements/_nosql/ -d=~/Dropbox/Elements/_jots/  "$@"
