#!/bin/sh
script="$0"
if [ -z $1 ]; then
    echo "Usage ${script##*/} <input_file> [<output_file>]"
    exit 1
fi
input_file="$1"
file_ext="${input_file##*.}"
if [ -z $2 ]; then
    output_dir=$(dirname "${input_file}")
    if [ $file_ext = "js" ]; then
        #output_file="${input_file%/*}/${input_file##*/}.min.js"
        output_file="${output_dir}/${input_file##*/}.min.js"
    fi
    if [ $file_ext = "css" ]; then
        #output_file="${input_file%/*}/${input_file##*/}.min.css"
        output_file="${output_dir}/${input_file##*/}.min.css"
    fi
else
    output_file=$2
fi
CDIR=$(dirname "$script")
YUICOMPRESSOR="${CDIR}/yuicompressor.jar"
if [ $file_ext = "js" ]; then
    java -jar $YUICOMPRESSOR --type js --nomunge --preserve-semi ${input_file} -o ${output_file} 
fi
if [ $file_ext = "css" ]; then
    java -jar $YUICOMPRESSOR --type css --nomunge --preserve-semi ${input_file} -o ${output_file}
fi
echo "output: ${output_file}"
