format='$directory$git_branch$git_status$character'

command_timeout=200
add_newline=false

[character]
success_symbol = "⌘(bold green)"

[directory]
truncation_symbol = "…/"
truncation_length = 1
truncate_to_repo = true

[git_branch]
symbol=""
# symbol="⑂"
format="[$symbol$branch]($style)"

[git_status]
